# Generated by Django 6.1.1 on 2026-09-25 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Etkinlik/Proje Adı')),
                ('tur', models.CharField(choices=[('proje', 'Proje'), ('etkinlik', 'Etkinlik'), ('gezi', 'Gezi'), ('spor', 'Sportif Müsabaka'), ('diger', 'Diğer')], default='etkinlik', max_length=50, verbose_name='Türü')),
                ('yil', models.IntegerField(verbose_name='Yapıldığı Yıl')),
                ('yarisma_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başvurulan Yarışma (Varsa)')),
                ('ogretmenler', models.TextField(verbose_name='Hazırlayan Öğretmenler')),
                ('ogrenciler', models.TextField(verbose_name='Hazırlayan Öğrenciler')),
                ('icerik', models.TextField(verbose_name='İçerik ve Detaylar')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='etkinlik_fotograflari/', verbose_name='Fotoğraf/Görsel')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('ekleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sisteme Giren Kullanıcı')),
            ],
            options={
                'verbose_name': 'Etkinlik/Proje',
                'verbose_name_plural': 'Etkinlikler ve Projeler',
                'ordering': ['-kayit_tarihi'],
            },
        ),
    ]
