# Generated by Django 6.1.1 on 2026-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='onaylandi',
            field=models.BooleanField(default=False, verbose_name='Onay Durumu'),
        ),
    ]
