# Generated by Django 6.1.1 on 2026-09-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0002_etkinlik_onaylandi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etkinlik',
            options={'ordering': ['-yil', '-kayit_tarihi'], 'verbose_name': 'Etkinlik/Proje', 'verbose_name_plural': 'Etkinlikler ve Projeler'},
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='basari',
            field=models.TextField(blank=True, null=True, verbose_name='Elde Edilen Başarı / Derece / Ödül'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='etkinlik_fotograflari/', verbose_name='Kapak Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='tur',
            field=models.CharField(choices=[('proje', 'Proje'), ('etkinlik', 'Etkinlik'), ('gezi', 'Gezi'), ('spor', 'Sportif Müsabaka'), ('diger', 'Diğer')], default='proje', max_length=50, verbose_name='Türü'),
        ),
        migrations.CreateModel(
            name='EtkinlikFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='etkinlik_fotograflari/', verbose_name='Fotoğraf')),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='etkinlikler.etkinlik', verbose_name='İlgili Faaliyet')),
            ],
            options={
                'verbose_name': 'Faaliyet Fotoğrafı',
                'verbose_name_plural': 'Faaliyet Fotoğrafları',
            },
        ),
    ]
